version: 2.1

orbs:
  node: circleci/node@7.0.0

jobs:
  test-perl:
    parameters:
      docker-image:
        type: string
        default: movabletype/test:buster
    docker:
      - image: << parameters.docker-image >>
    steps:
      - checkout
      - run:
          name: Test
          command: |
            git clone -b develop --depth 1  https://github.com/movabletype/movabletype.git mt
            cp -r mt/* .
            cp mt/.proverc .
            prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/MFA/t

  build:
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - run:
          name: Install build dependency
          command: |
            sudo apt update
            sudo apt --no-install-recommends -y install libjson-perl libyaml-perl
      - run:
          name: Build
          command: |
            perl Makefile.PL --version $(git describe --tags | sed -e 's/^v//')
            make manifest
            make zipdist
            make dist
            mkdir -p packages
            mv MFA-* packages
      - store_artifacts:
          path: packages

workflows:
  version: 2
  test-and-build:
    jobs:
      - test-perl:
          name: test-perl with buster
          docker-image: movabletype/test:buster
      - test-perl:
          name: test-perl with bullseye
          docker-image: movabletype/test:bullseye
      - test-perl:
          name: test-perl with cloud7
          docker-image: movabletype/test:cloud7
      - build
  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
